package rxjava;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import io.reactivex.*;

import java.util.Random;
import java.util.concurrent.TimeUnit;


public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static Observable<Integer> fakeUserInputByTimeInterval() {
        Random random = new Random();
        return Observable.intervalRange(0,20,500,500, TimeUnit.MILLISECONDS)
                .map(v->random.nextInt(20));
    }

    public static Observable<Integer> fakeUserInputByTimeRandomInterval() {
        Random random = new Random();
        return Observable.intervalRange(0,20,500,500, TimeUnit.MILLISECONDS)
                .concatMap(number->Observable.just(random.nextInt(20))
                        .delay(random.nextInt(500),TimeUnit.MILLISECONDS));
    }


    public static Observable<Integer> filterInput() {
        return Observable.just(10,3,5,14,5)
                .filter(number->number%2==0);
    }

    public static Observable<Integer> fakeUserInput() {
        Random random = new Random();

        return Observable.just(10,3,5,13)
                .map(number->random.nextInt(20));
    }

    public static void main(String[] args) {
//        filterInput()
//                .subscribe(line->System.out.println(line));
//    fakeUserInput()
//            .subscribe(line->System.out.println(line));

//    fakeUserInputByTimeInterval()
//            .blockingSubscribe(line->System.out.println(line));
        fakeUserInputByTimeRandomInterval()
                .blockingSubscribe(line->System.out.println(line));


    }
}
